### ISSUE TITLE
Streamline the install process: remove the need to execute webservicesetup.php

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qbank_gitsync#11]
This is an unusual step for a Moodle install:
https://github.com/maths/moodle-qbank_gitsync/blob/20b65830752081460baeea22576e80ce02a2b2ec/doc/webservicesetup.md?plain=1#L5
Many users won't be able to run a command line php.  Can we roll this into the install process?

**Comment by EJMFarrow** [comment]
I did try the install.php file a while ago and one thing that would have been really useful to automate - re-enabling the 'allow file upload' option for the webservice after a gitsync upgrade - wasn't possible due to ordering issues. 

Everything in the script can be done via the site admin pages if necessary so going to close this.
